### ISSUE TITLE
Image comparison is failing for same image if images pixels  are different

### ISSUE THREAD

**Issue by ReddyManjunath** [pazone/ashot#148] opened 2019-06-04 13:40 UTC
Scenario : Image comparison on different browsers

1.Launch the URL in IE browser and capture the screenshots image 1
2.Launch the same URL in Chrome browser and capture image 2
3.Compare Image 1 and Image 2 

Issue: Image comparison is failing for the same image but both the image pixels are different.

Image 1 pixel : 1006*614
Image 2 pixel : 1366*657

How to overcome this issue, also is there any way to capture the image with standerd same pixels across FF,IE,GC browsers.

**Comment by JAnton101** [comment] 2019-08-12 10:55
Hi, overall it's a bad idea to compares screenshots across different browsers because of the nature of this type of software. Each browser uses own engine with own rendering rules, thus it's quite hard to achieve pixel perfect layout on different browsers, more you are able to google by words "Why does my website look different on different browsers?"

Thus it's not a bug, it's a feature, just keep it in mind and compare screens in the same browsers.

Please close this issue.

**Closed as completed** 2019-09-20 07:18 UTC
